export const PRODUCTS = [
    { id: "01", image: { imageSrc: 'assets/image/life_ring.png' }, name: 'computer Book', number: '10', price: '120', company: 'computer Swimlane' },
    { id: "02", image: { imageSrc: 'assets/image/heart.png' }, name: 'computer Pen', number: '20', price: '130', company: 'KFC' },
    { id: "03", image: { imageSrc: 'assets/image/lock.png' }, name: 'computer Ruler', number: '30', price: '140', company: 'computer Burger King' },
    { id: "04", image: { imageSrc: 'assets/image/life_ring.png' }, name: 'computer', number: '40', price: '150', company: 'HUST' },
    { id: "05", image: { imageSrc: 'assets/image/heart.png' }, name: 'Laptop', number: '50', price: '160', company: 'NUDT' },
    { id: "06", image: { imageSrc: 'assets/image/lock.png' }, name: 'Desktop', number: '60', price: '70', company: 'computer Chang' },
    { id: "07", image: { imageSrc: 'assets/image/test_image.png' }, name: 'computer Newton', number: '70', price: '60', company: 'Sha' },
    { id: "08", image: { imageSrc: 'assets/image/credit_background_1.png' }, name: 'computer Einstein', number: '80', price: '50', company: 'computer Bei' },
    { id: "09", image: { imageSrc: 'assets/image/credit_background_6.png' }, name: 'computer Prandtl', number: '90', price: '420', company: 'Jing' },
    { id: "10", image: { imageSrc: 'assets/image/test_image.png' }, name: 'computer Tree', number: '100', price: '120', company: 'Shang' },
    { id: "11", image: { imageSrc: 'assets/image/credit_background_1.png' }, name: 'computer Flower', number: '110', price: '320', company: 'computer Hai' },
    { id: "12", image: { imageSrc: 'assets/image/credit_background_6.png' }, name: 'Animal', number: '120', price: '220', company: 'Burger' },
    { id: "13", image: { imageSrc: 'assets/image/life_ring.png' }, name: 'computer Book', number: '10', price: '120', company: 'computer Swimlane' },
    { id: "22", image: { imageSrc: 'assets/image/heart.png' }, name: 'computer Pen', number: '20', price: '130', company: 'KFC' },
    { id: "23", image: { imageSrc: 'assets/image/lock.png' }, name: 'computer Ruler', number: '30', price: '140', company: 'computer Burger King' },
    { id: "24", image: { imageSrc: 'assets/image/life_ring.png' }, name: 'computer', number: '40', price: '150', company: 'HUST' },
    { id: "25", image: { imageSrc: 'assets/image/heart.png' }, name: 'Laptop', number: '50', price: '160', company: 'NUDT' },
    { id: "26", image: { imageSrc: 'assets/image/lock.png' }, name: 'Desktop', number: '60', price: '70', company: 'computer Chang' },
    { id: "27", image: { imageSrc: 'assets/image/test_image.png' }, name: 'computer Newton', number: '70', price: '60', company: 'Sha' },
    { id: "28", image: { imageSrc: 'assets/image/credit_background_1.png' }, name: 'computer Einstein', number: '80', price: '50', company: 'computer Bei' },
    { id: "29", image: { imageSrc: 'assets/image/credit_background_6.png' }, name: 'computer Prandtl', number: '90', price: '420', company: 'Jing' },
    { id: "30", image: { imageSrc: 'assets/image/test_image.png' }, name: 'computer Tree', number: '100', price: '120', company: 'Shang' },
    { id: "31", image: { imageSrc: 'assets/image/life_ring.png' }, name: 'computer Book', number: '10', price: '120', company: 'computer Swimlane' },
    { id: "32", image: { imageSrc: 'assets/image/heart.png' }, name: 'computer Pen', number: '20', price: '130', company: 'KFC' },
    { id: "33", image: { imageSrc: 'assets/image/lock.png' }, name: 'computer Ruler', number: '30', price: '140', company: 'computer Burger King' },
    { id: "34", image: { imageSrc: 'assets/image/life_ring.png' }, name: 'computer', number: '40', price: '150', company: 'HUST' },
    { id: "35", image: { imageSrc: 'assets/image/heart.png' }, name: 'Laptop', number: '50', price: '160', company: 'NUDT' },
    { id: "36", image: { imageSrc: 'assets/image/lock.png' }, name: 'Desktop', number: '60', price: '70', company: 'computer Chang' },
    { id: "37", image: { imageSrc: 'assets/image/test_image.png' }, name: 'computer Newton', number: '70', price: '60', company: 'Sha' },
    { id: "38", image: { imageSrc: 'assets/image/credit_background_1.png' }, name: 'computer Einstein', number: '80', price: '50', company: 'computer Bei' },
    { id: "39", image: { imageSrc: 'assets/image/credit_background_6.png' }, name: 'computer Prandtl', number: '90', price: '420', company: 'Jing' },
    { id: "40", image: { imageSrc: 'assets/image/test_image.png' }, name: 'computer Tree', number: '100', price: '120', company: 'Shang' },
    { id: "41", image: { imageSrc: 'assets/image/life_ring.png' }, name: 'computer Book', number: '10', price: '120', company: 'computer Swimlane' },
    { id: "42", image: { imageSrc: 'assets/image/heart.png' }, name: 'computer Pen', number: '20', price: '130', company: 'KFC' },
    { id: "43", image: { imageSrc: 'assets/image/lock.png' }, name: 'computer Ruler', number: '30', price: '140', company: 'computer Burger King' },
    { id: "44", image: { imageSrc: 'assets/image/life_ring.png' }, name: 'computer', number: '40', price: '150', company: 'HUST' },
    { id: "45", image: { imageSrc: 'assets/image/heart.png' }, name: 'Laptop', number: '50', price: '160', company: 'NUDT' },
    { id: "46", image: { imageSrc: 'assets/image/lock.png' }, name: 'Desktop', number: '60', price: '70', company: 'computer Chang' },
    { id: "47", image: { imageSrc: 'assets/image/test_image.png' }, name: 'computer Newton', number: '70', price: '60', company: 'Sha' },
    { id: "48", image: { imageSrc: 'assets/image/credit_background_1.png' }, name: 'computer Einstein', number: '80', price: '50', company: 'computer Bei' },
    { id: "49", image: { imageSrc: 'assets/image/credit_background_6.png' }, name: 'computer Prandtl', number: '90', price: '420', company: 'Jing' },
    { id: "50", image: { imageSrc: 'assets/image/test_image.png' }, name: 'computer Tree', number: '100', price: '120', company: 'Shang' }

];
